# Generated by Django 4.2 on 2023-07-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Footing_Isolated",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("footing_length", models.IntegerField()),
                ("footing_breadth", models.IntegerField()),
                ("input_depth1", models.IntegerField()),
                ("input_depth2", models.IntegerField()),
                ("concrete_grade", models.TextField()),
                ("rebar_grade", models.TextField()),
                ("soling_type", models.TextField()),
                ("pcc_grade", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
